name: ST-Gacha
main: net.starly.gacha.GachaMain
author: Starly Team
website: http://starly.kr/

description: Gacha Plugin.

softdepend:
  - ST-Core

version: 1.0.1
api-version: 1.13

permissions:
  starly.gacha.create:
    description: 가챠생성
    default: op
  starly.gacha.delete:
    description: 가챠삭제
    default: op
  starly.gacha.reward:
    description: 보상설정
    default: op
  starly.gacha.reload:
    description: 리로드
    default: op
  starly.gacha.roll:
    description: 뽑기
    default: op
  starly.gacha.*:
    children:
      - starly.gacha.create
      - starly.gacha.delete
      - starly.gacha.reward
      - starly.gacha.roll

commands:
  가챠:
    description: A Gacha Command.