name: ST-Gacha # TODO: 수정
main: net.starly.gacha.GachaMain # TODO: 수정
author: Starly Team
website: http://starly.kr/

description: Gacha Plugin. # TODO: 수정

softdepend:
  - ST-Core

version: 1.0
api-version: 1.13

permissions:
  starly.gacha.admin:
    description: 가챠 관리자 명령어 권한
    default: op

commands:
  가챠:
    description: A Gacha Command.